# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:7.10

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: init　All
          command: |
            rm -rf node_modules
            yarn cache clean
            yarn install
            node_modules/.bin/webpack
      - run:
          name: System information
          command: |
            echo "Node $(node -v)"
            echo "Yarn v$(yarn --version)"
            pwd
      - run:
          name: Install dependencies
          command: yarn
      - run: yarn run build_dist

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: System information 2nd
          command: |
            ls -latr
            ls -latr ./dist
            pwd
            ls -latr ~/repo/dist

      # run tests!
      #- run: yarn test

      - store_artifacts:
          path: artifacts/
          path: ~/repo/dist
